(function(){(function(l,y,q,e){function h(a,b){return 0==={}.toString.call(a).indexOf("[object "+b)}function I(){}function z(a){return n&&!J.test(a)?("/"===n.charAt(n.length-1)?n:n+"/")+a:a}function B(a){var b=a.substr(0,a.lastIndexOf("/"));a=a.replace(C,b+"/");var c={baseName:b,a:{},d:{id:a,uri:z(a)},require:function(a,b){return K(a,b||I,c)}};c.require.toUrl=z;return c}function w(a){var b=[],c,d,m,t,k;d=function(a,c){b.push([a,c])};m=function(a){k(q,a)};t=function(a){k(!1,a)};k=function(a,c){d=a?function(a){a&&
a(c)}:function(a,b){b&&b(c)};m=t=function(){throw Error("Promise already completed.");};for(var f,k=0;f=b[k++];)(f=f[a?0:1])&&f(c)};c={then:function(a,b){d(a,b);return this},resolve:function(a){m(a)},reject:function(a){t(a)}};a&&(c.name=a);return c}function L(a){var b=y.createElement("script");b.type="text/javascript";b.onload=b.onreadystatechange=function(b){b=b||l.event;if("load"===b.type||M[this.readyState]){delete x[a.name];this.onload=this.onreadystatechange=this.onerror=null;if("js"==a.prefix)return a.resolve();
b=u;u=e;a.e!==q&&(b?b.b?a.reject(Error(b.b.replace("${url}",a.url))):D(a,b):a.reject(Error("Missing define(): "+a.url)))}};b.onerror=function(){a.reject(Error("Syntax error or http error: "+a.url))};b.async=q;b.src=a.url;x[a.name]=b;E.insertBefore(b,E.firstChild)}function F(a,b,c,d){function m(a){return function(b){k[a]=b;0===--r&&(e=q,c(k))}}function t(a){e=q;d(a)}for(var k=[],r=a.length,l=r,f=0,e=!1;f<l&&!e;f++)if("require"===a[f])k[f]=b.require,r--;else if("exports"===a[f])k[f]=b.a,r--;else if("module"===
a[f])k[f]=b.d,r--;else{var p=a[f].indexOf("!"),g=(0<=p?a[f].substr(p+1):a[f]).replace(C,b.baseName+"/"),p=0<=p?a[f].substr(0,p):"",h=v[p+g],n=z(g);h||(h=v[p+g]=w(g),h.url=N.test(n)?n:n+".js",h.prefix=p,L(h));h.then(m(f),t)}0!==r||e||c(k)}function D(a,b){var c=B(a.name);F(b.c,c,function(d){(d=b.f.apply(c.a,d))&&d.amd&&h(d.then,"Function")?d.then(a.resolve,a.reject):a.resolve(d!==e?d:c.a)},a.reject)}function K(a,b,c){if(h(a,"String")){c=v[a];var d;c&&c.then(function(a){d=a});if(d===e)throw Error("Module is not already resolved: "+
a);return d}F(a,c,function(a){b.resolve?b.resolve(a):b.apply(null,a)},function(a){if(b.reject)b.reject(a);else throw a;})}function A(a,b){var c=B(""),d=w(),m={then:function(a,b){d.then(function(b){a&&a.apply(null,b)},function(a){if(b)b(a);else throw a;});return m},next:function(a,b){var e=d;d=w();e.then(function(){c.require(a,d)});b&&d.then(b);return m}},e;b&&m.then(b);e=c.require(a,d);return h(a,"String")?e:m}function O(a){var b,c,d,e,g=a.length;d=a[g-1];e=h(d,"Function");2===g?h(a[0],"Array")?c=
a[0]:b=a[0]:3===g&&(b=a[0],c=a[1]);!c&&e&&0<d.length&&(c=["require","exports","module"]);return{name:b,c:c||[],f:e?d:function(){return d}}}function G(){var a=O(arguments),b=a.name;if(b===e)if(u!==e)u={b:"Too many anon defines: ${url}"};else{a:{if(!h(l.opera,"Opera"))for(var c in x)if("interactive"===x[c].readyState){b=c;break a}b=void 0}b||(u=a)}b!==e&&((c=v[b])||(c=v[b]=w(b)),c.e=q,D(c,a))}function P(a){var b;a=a({push:function(a){b[a.shift()?"then":"next"].apply(b,a)}});b=A(a[1],a[2]);for(var c=
0;c<a[0].length;c++)b[a[0][c].shift()?"then":"next"].apply(b,a[0][c])}var H=l.glam||(l.glam={}),g=H.create||(H.create={});if(g.require===e||g.require.min===q)if(g.jsbase==e)l.console&&l.console.log("ldr: base undef");else{var E=y.head||y.getElementsByTagName("head")[0],n=g.jsbase,v={},u,x={},J=/^\/|^[^:]*:\/\//,C=/^\.(\/|$)/,N=/\.js$/,M={loaded:1,interactive:1,complete:1};A.version="0.5";G.amd={};g.define=G;g.require.min=!1;setTimeout(function(){g.require=A;if(l._glmrqr)for(var a=0;a<l._glmrqr.length;a++)P(l._glmrqr[a])},
0)}})(this,document,!0);})();

(function(){glam.create.define("events",function(){function f(a,b){setTimeout(function(a,b){return function(){a.apply(null,b)}}(a,b),0)}var c=window.glam||(window.glam={}),c=c.create||(c.create={}),b={};c.ev||(c.ev={listen:function(a,c){void 0==b[a]&&(b[a]=[]);b[a].push(c)},unlisten:function(a,c){if(void 0!=b[a])for(var d=0,e=b[a].length;d<e;d++)b[a][d]===c&&b[a].splice(d,1)},fire:function(a,c){if(void 0!=b[a]&&0!==b[a].length)for(var d=0,e,g=Array.prototype.slice.call(arguments,1);e=b[a][d++];)f(e,g)}});return c.ev});})();

(function(){glam.create.define("flash",function(){function g(b,c,g,h,a){if(f&&f>=(h||9)){a||(a={});"string"===typeof a.wmode||(a.wmode="opaque");"string"===typeof a.allowScriptAccess||(a.allowScriptAccess="always");"string"===typeof a.allowFullScreen||(a.allowFullScreen="true");a.id||(a.id="gflid"+Math.floor(1E6*Math.random()));a.name||(a.name=a.id);if(d.plugins&&d.mimeTypes&&d.mimeTypes.length){a.type="application/x-shockwave-flash";a.src=b;a.width=c;a.height=g;a.style="outline:0";b="<embed";for(var e in a)a.hasOwnProperty(e)&&
(b+=" "+e+'="'+a[e]+'"');b+=" /></embed>"}else{a.movie=b;e={width:c,height:g,classid:"clsid:D27CDB6E-AE6D-11CF-96B8-444553540000",id:a.id};b="<object";for(var k in e)e.hasOwnProperty(k)&&(b+=" "+k+'="'+e[k]+'"');b+=">";for(var l in a)a.hasOwnProperty(l)&&(b+='<param name="'+l+'" value="'+a[l]+'" />');b+="</object>"}return b}return!1}var d=navigator,f=!1;if(d.plugins&&d.mimeTypes&&d.mimeTypes.length){var c=d.plugins["Shockwave Flash"];c&&c.description&&(f=parseInt(c.description.match(/[0-9]+/)[0],
10))}else if(void 0!=window.ActiveXObject)try{if(c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")){var h=c.GetVariable("$version");h&&(f=parseInt(h.split(" ")[1].split(",")[0],10))}}catch(m){}f&&!window.trkpx&&(window.trkpx=function(b){(new Image).src=b.replace("%n",+new Date+"-"+Math.floor(1E5*Math.random()))});g.majorVersion=f;return g});})();

(function(){glam.create.define("uit",function(){function e(a,b,c){a.addEventListener?a.addEventListener(b,c,0):a.attachEvent&&a.attachEvent("on"+b,c)}function f(a,b,c){a.removeEventListener?a.removeEventListener(b,c,0):a.detachEvent&&a.detachEvent("on"+b,c)}function d(a){this.a=a;this.c=this.l=this.e=this.i=this.j=this.m=this.p=this.g=this.b=0;this.n=null;var b=this,c={x:0,y:0};this.o=function(a){a=b.q(a);var h=+new Date;if(a.x!=c.x||a.y!=c.y)b.p=h;c=a};this.k=function(a){var c;a||(a=window.event);a.target?c=
a.target:a.srcElement&&(c=a.srcElement);b.s(c)};this.f=function(a){var c;a||(a=window.event);a.target?c=a.target:a.srcElement&&(c=a.srcElement);b.r(c)}}d.prototype={h:50,d:6E4,q:function(a){a||(a=window.event);return a.pageX?{x:a.pageX,y:a.pageY}:{x:a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,y:a.clientY+document.body.scrollTop+document.documentElement.scrollTop}},t:function(){if(!this.e&&(this.e=1,this.a.startTimer("uitf"),this.c<this.d)){this.l=+new Date;this.a.startTimer("uit");
var a=this;this.n=setTimeout(function(){a.a.stopTimer("uit");a.c=a.d},this.d-this.c)}},u:function(){this.e&&(this.e=0,this.a.stopTimer("uitf"),this.c<this.d&&(this.a.stopTimer("uit"),clearTimeout(this.n),this.c+=+new Date-this.l))},s:function(a){var b=this;"y"!==a.getAttribute("glm-uit-hvrng")&&(this.b++,a.setAttribute("glm-uit-hvrng","y"),1<this.b||0!==this.g&&+new Date-this.g<=this.h||(this.a.track("mousehover"),setTimeout(function(){b.b&&(b.i||(b.a.stopTimer("art"),b.i=1),b.a.track("mouseover",
"qualified"),function g(){b.b&&(200>+new Date-b.p?(b.m||(b.a.track("mouseover","iab"),b.m=1),b.t()):setTimeout(g,200))}())},500),e(document,"mousemove",this.o)))},r:function(a){if("y"===a.getAttribute("glm-uit-hvrng")&&this.b){var b=this;this.b--;a.removeAttribute("glm-uit-hvrng");this.g=+new Date;setTimeout(function(){b.b||(b.u(),f(document,"mousemove",b.o))},this.h+1)}},v:function(a){this.j||(this.a.startTimer("art"),this.j=1);e(a,"mouseover",this.k);e(a,"mouseout",this.f)},detach:function(a){f(a,
"mouseover",this.k);f(a,"mouseout",this.f);"y"===a.getAttribute("glm-uit-hvrng")&&this.f({target:a})}};d.prototype.attach=d.prototype.v;d.prototype.detach=d.prototype.detach;return d});})();

(function(){glam.create.define("inview",["events"],function(h){function g(a,b){if(window.getComputedStyle)return document.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function t(a,b){var c={top:Math.max(a.top,b.top),left:Math.max(a.left,b.left),bottom:Math.min(a.bottom,b.bottom),right:Math.min(a.right,b.right),hidden:a.hidden};c.d=c.right-c.left;c.c=c.bottom-c.top;return c}function m(){var a;a=d.documentElement.clientHeight;var b=d.documentElement.clientWidth;a={d:b,c:a,
top:0,bottom:a,left:0,right:b,hidden:n?d[f]:0};for(var b=0,c=p.length;b<c;b++)p[b].D(a).r();clearTimeout(u);u=setTimeout(m,n&&d[f]?1E4:100)}function e(a,b,c,d,e,f,g){var l=this;this.l=a;this.o=!a;this.f=b;this.k=c?parseInt(c,10):!1;this.j=d?parseInt(d,10):!1;this.g=g||Math.floor(1E8*Math.random());this.u=f;this.b=(e?e:"in-view")+(k?"":"-unconfirmed");this.duration=this.left=this.bottom=this.right=this.top=this.c=this.d=0;this.n=this.e=this.i=!1;this.p=function(a){l.n=a;l.r()};h.listen("flash-fullscreen-"+
this.g,this.p);this.f.track(this.b,"init")}var r=0,v=0;self!=top&&(!0===window.inDapIF&&window.pub_iframe?r=1:(v=1,window.console&&window.console.log("Not in friendly iframe")));var d=(r?top:window).document,f,q,n,k,u,p=[];void 0!==d.hidden?(f="hidden",q="visibilitychange"):void 0!==d.mozHidden?(f="mozHidden",q="mozvisibilitychange"):void 0!==d.webkitHidden&&(f="webkitHidden",q="webkitvisibilitychange");k=(n=void 0!==d.addEventListener&&void 0!==f)&&!v;e.prototype={s:function(a,b){b&&(this.A=this.hidden,
this.hidden=!1);if(a&&9!==a.nodeType){var c=a.parentNode;if(c)if("0"===g(a,"opacity")||"none"===g(a,"display")||"hidden"===g(a,"visibility"))this.hidden=!0,this.A||this.f.track(this.b,b?"warning-hidden":"warning-parent-hidden");else{var d=g(a,"overflow");if(!b&&("hidden"===d||"scroll"===d)){var e=a.getBoundingClientRect();this.a=t(this.a,e);"scroll"===d&&(this.m=t(this.m,e))}return this.s(c,!1)}else this.hidden=!0,this.A||this.f.track(this.b,"warning-not-in-dom")}},D:function(a){this.m=this.a=a;if(this.e||
this.o)return this;a=this.l.getBoundingClientRect();this.top=a.top;this.left=a.left;this.bottom=this.j?a.top+this.j:a.bottom;this.right=this.k?a.left+this.k:a.right;this.d=this.k?this.k:a.right-a.left;this.c=this.j?this.j:a.bottom-a.top;this.t=242500<this.d*this.c;this.l&&this.s(this.l,!0);return this},B:function(){var a,b;this.top>=this.a.bottom||this.bottom<=this.a.top?a=0:(a=this.c,this.top<this.a.bottom&&this.bottom>this.a.bottom&&(a-=this.bottom-this.a.bottom),this.bottom>this.a.top&&this.top<
this.a.top&&(a-=this.a.top-this.top));this.left>=this.a.right||this.right<=this.a.left?b=0:(b=this.d,this.left<this.a.right&&this.right>this.a.right&&(b-=this.right-this.a.right),this.right>this.a.left&&this.left<this.a.left&&(b-=this.a.left-this.left));a*=b;b=this.t?this.d*this.c:Math.min(this.d,this.m.d)*Math.min(this.c,this.m.c);return 0===b?0:a/b},r:function(){var a,b=+new Date,c;this.e?a=!1:this.n?a=!0:this.a.hidden?a=!1:this.o?a=!0:this.hidden?a=!1:(a=this.B(),a=this.t?.3<=a:.5<=a);!a&&this.i&&
(c="hide",this.i=!1,this.f.stopTimer(this.b),this.q&&(this.duration+=b-this.q),h.fire(this.b+"-"+this.g,!1));a&&!this.i&&(c="show",this.i=!0,this.f.startTimer(this.b),this.v=0,this.q=b,h.fire(this.b+"-"+this.g,!0),this.n&&setTimeout(m,1050));!this.v&&a&&1E3<b-this.q&&(c="qualified",this.f.track(this.b,"qualified"),this.v=1,this.C||(this.f.track(this.b,"impression"),this.C=1));c&&"function"==typeof this.u&&this.u(c);return this}};e.prototype.resize=function(a,b){!1!==this.l&&(this.k=a?parseInt(a,10):
!1,this.j=b?parseInt(b,10):!1)};e.prototype.setFloat=function(a){this.o=!!a};e.prototype.isVisible=function(){return this.i};e.prototype.isConfirmed=function(){return k};e.prototype.isRemoved=function(){return this.e};e.prototype.remove=function(){this.e||(h.unlisten("flash-fullscreen-"+this.g,this.p),this.e=!0,this.r())};e.prototype.unremove=function(){this.e&&(h.listen("flash-fullscreen-"+this.g,this.p),this.e=!1)};return function(a,b,c,f,g,h){var k,l;c&&"object"==typeof c&&(k=c.w,f=c.h,g=c.event_base,
h=c.onChange,l=c.edge_id);a==document&&(a=!1);!1!==a&&r&&(a=pub_iframe);c=p.length;a=new e(a,b,k,f,g,h,l);p.push(a);0===c&&(m(),n&&d.addEventListener(q,m,!1));return a}});})();
