(function(e,m,q){function r(b,a){return b===q?"":b.length>a?b.substr(0,a):b}function u(b,a,d,c){e.console&&e.console.log&&e.console.log("event "+b+":"+a+" after "+d+"ms on :"+c)}function F(b){for(var a=0,d=0;500>d-b||2<a;a++)d=1E3*Math.pow(Math.ceil(Math.pow(b/1E3,1/1.75))+a,1.75);6E5<d&&(d=6E5);return d-b}function s(b,a,d,c,g,f){b="b=5555&m=3333&v=2&t=s&i="+l(a)+"&g="+l(c)+"&d="+l(b)+"&edge="+l(d)+"&p="+l(e.glam_affiliate_id||"")+"&w=";if(y)a=y();else{a=n;c=a.indexOf("?");-1<c&&(a=a.slice(0,c));
for(var v=c=0;v<a.length;v++)c<<=1,0>c&&(c|=1),c^=a.charCodeAt(v);a=(c&2147483647).toString(36).slice(-6);a="000000".substring(a.length)+a;c=Math.floor((+new Date-11991456E5)/1E3).toString(36).slice(-6);c="000000".substring(c.length)+c;a=a+c+Math.random().toString(36).slice(-2)}b=b+a+"&s="+(z?z():"");w&&(b+="&cc="+w("country_code")+"&rc="+w("region_code"));this.id=d;this.N=b;this.G=!1;this.g={};this.i={};this.p=g;this.A=0;this.a={I:f||1}}function A(){return{c:!1,f:[{s:2,name:"rv2"},{s:7,name:"rv7"},
{s:15,name:"rv15"},{s:30,name:"rv30"}],D:null,d:0}}function t(b,a){function d(){b.a.b[a].f.length&&(b.a.b[a].D=setTimeout(function(){if(b.a.b[a].c){var c=b.a.b[a].f.shift(),f=+new Date;b.track(f,c.name,a);b.a.b[a].d+=f-b.a.b[a].w;b.a.b[a].w=f;d()}},1E3*b.a.b[a].f[0].s-b.a.b[a].d))}var c=!!b.a.F&&!!b.a.e[a];b.a.b||(b.a.b={});b.a.b[a]||(b.a.b[a]=A());c!=!!b.a.b[a].c&&((b.a.b[a].c=c)?(b.a.b[a].w=+new Date,b.startTimer(+new Date,"realview_"+a),d()):(b.stopTimer(+new Date,"realview_"+a),b.a.b[a].d+=+new Date-
b.a.b[a].w,clearTimeout(b.a.b[a].D)))}function B(){this.f=[];this.J=this.B=!1;this.t=this.m=""}function x(b){e.console&&e.console.error&&e.console.error(Array.prototype.slice.call(arguments))}function C(b){if(b.length&&1<b.length){var a="x"+b[0],d=b[1],c=Array.prototype.slice.call(b,2);"init"==d?"object"!==typeof c[0]?x("Empty conf",b):(h[a]=new s(c[0].adId,c[0].creativeId,c[0].edgeId||"",c[0].adTile,c[0].load,c[0].rv_ver),c[0].noimpression||h[a].startTimer(c[0].load,"im"),c[0].nodwell||D.add(h[a])):
h[a]instanceof s?("trk"==d&&h[a].track.apply(h[a],c),"start"==d&&h[a].startTimer.apply(h[a],c),"stop"==d&&h[a].stopTimer.apply(h[a],c),"dest"==d&&(h[a].M(),h[a]=null)):null!==h[a]&&x("Undefined backend",b)}else x("Invalid item",b)}e.glam||(e.glam={});var l=encodeURIComponent,w=e.GlamGetGeoData,z=e.GlamGetSessionId,y=e.GlamGetPageViewIdN,k=[],p=[],n=e.location.href,n=-1<n.indexOf("#")?n.slice(0,n.indexOf("#")):n;s.prototype={r:function(b){var a=this,d=+new Date;if(0===b)a.timeout&&clearTimeout(a.timeout),
a.q=q,a.H();else if(b||(b=1),d+b<a.A+1E3&&(b=1E3-(d-a.A)),!a.q||a.q>d+b)a.q=d+b,a.timeout&&clearTimeout(a.timeout),a.timeout=setTimeout(function(){a.H()},b)},M:function(){this.timeout&&clearTimeout(this.timeout)},track:function(b,a,d,c){a=r(a,32);d=r(d,32);c=r(c,256);b-=this.p;var g=a+(d?":"+d:"");u("occurred",g,b,this.id);this.g[g]||(this.g[g]={u:a,j:d,l:c,n:[],k:0});this.g[g].n.push(b);this.g[g].k++;this.r("exit"===a?0:1);if(p)for(var f in p)p.hasOwnProperty(f)&&p[f].match.test(a+":"+d)&&p[f].h(this,
a,d,c)},startTimer:function(b,a,d){a=r(a,32);d=r(d,256);b-=this.p;0===b&&b++;u("started",a,b,this.id);this.i[a]||(this.i[a]={u:"timer",j:a,L:b,l:d,d:0,k:0,c:0,v:0});var c=this.i[a];if(!c.c&&(c.v||(c.C=b,c.c=1,c.o=0,c.k++,this.r()),k))for(var g in k)k.hasOwnProperty(g)&&k[g].match.test(a)&&k[g].h(this,!0,a,d)},stopTimer:function(b,a){a=r(a,32);var d=b-this.p;u("stopped",a,d,this.id);var c=this.i[a];if(c&&c.c&&(c.d+=d-c.C,c.o=1,c.c=0,this.r(),k))for(var g in k)k.hasOwnProperty(g)&&k[g].match.test(a)&&
k[g].h(this,!1,a)},H:function(){var b=this,a=+new Date,d=a-this.p,c,g,f,e;g=[];for(var h in this.g)this.g.hasOwnProperty(h)&&(f=this.g[h],0<f.n.length&&(e="e:"+l(f.u)+",c:"+f.k+",s:"+f.n.join("+"),f.j&&(e+=",n:"+l(f.j)),f.l&&(e+=",p:"+l(f.l)),g.push(e),f.n=[]));for(var k in this.i)this.i.hasOwnProperty(k)&&(f=this.i[k],f.v||!f.c&&!f.o||(h=f.d+(d-f.C),f.o&&(f.o=0,h=f.d),6E5<=h?(f.v=1,h=6E5):f.c&&(e=F(d-f.C),c=c?Math.min(e,c):e),e="e:"+l(f.u)+",c:"+f.k+",s:"+f.L+",d:"+h,f.j&&(e+=",n:"+l(f.j)),f.l&&
(e+=",p:"+l(f.l)),g.push(e)));g.length&&function G(a){var c=0,d="&a=e&"+b.N,f;b.G||(d+="&o="+l(n),b.G=1);d+="&e=";for(f=d.length;a.length;)if(1960>(f+=a[0].length))d+=a.shift()+";",c++;else if(1840<a[0].length)a.shift();else break;c&&(c=d,d=Math.random().toString(36).slice(-4),(new Image).src="http://www13.glam.com/clear.gif?r="+d+c);a.length&&G(a)}(g);this.A=a;this.q=q;c&&this.r(c)}};k.push({match:/^in\-view/,h:function(b,a){if(1===b.a.I){b.a.F=a;for(var d in b.a.e)b.a.e.hasOwnProperty(d)&&t(b,d)}}});
k.push({match:/^player\-iv/,h:function(b,a){if(2===b.a.I){b.a.F=a;for(var d in b.a.e)b.a.e.hasOwnProperty(d)&&t(b,d)}}});k.push({match:/^videoplay|^video\d+/,h:function(b,a,d){b.a.e||(b.a.e={});var c=/^(?:videoplay|video)_?([\w_:-]+)?/.exec(d)[1]||"single";(d=/^video(\d+)/.exec(d))&&(c="tab_"+d[1]);b.a.e[c]=a;t(b,c)}});p.push({match:/^videoend/,h:function(b,a,d){a=d||"single";b.a.e&&b.a.e[a]&&(b.a.e[a]=!1,t(b,a));for(;d=b.a.b[a].f.shift();)b.track(+new Date,d.name,a);b.a.b[a]=A()}});p.push({match:/^videostart/,
h:function(){e._comscore=e._comscore||[];e._comscore.push({c1:"1",c2:"6035233",c5:"02"});var b=m.createElement("script"),a=m.getElementsByTagName("script")[0];b.async=!0;b.src=("https:"==m.location.protocol?"https://sb":"http://b")+".scorecardresearch.com/beacon.js";a.parentNode.insertBefore(b,a)}});B.prototype={add:function(b){this.f.push(b);this.B||this.K();this.J?(b.track(+new Date,"init","page-dwell-modern"),m[this.m]||b.startTimer(+new Date,"page-dwell-modern")):b.startTimer(+new Date,"page-dwell-legacy")},
K:function(){var b=this;this.B=!0;m.hidden!==q?(this.m="hidden",this.t="visibilitychange"):m.webkitHidden!==q&&(this.m="webkitHidden",this.t="webkitvisibilitychange");m.addEventListener!==q&&this.t&&(this.J=!0,m.addEventListener(this.t,function(){for(var a=0;a<b.f.length;a++)m[b.m]?b.f[a].stopTimer(+new Date,"page-dwell-modern"):b.f[a].startTimer(+new Date,"page-dwell-modern")},!1))}};var E=e._gmtrcs;if(!0!==E.B){Array.prototype.map||(Array.prototype.map=function(b,a){var d=+this.length;if("function"!==
typeof b)throw new TypeError;for(var c=Array(d),e=0;e<d;e++)e in this&&(c[e]=b.call(a,this[e],e,this));return c});var D=new B,h={};E.map(C);e._gmtrcs={setup:!0,push:C};e.no_glm_pg_dwell||D.add(new s("-2","-1",e.glam_pvid||"-1","",+new Date))}})(window,document);
